packages:
  - pipeline
  - website
allowedDeprecatedVersions:
  glob: '*'
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - start-server-and-test@3.0.6
